project_id = "zuluogrlwqehvhxpqjok"

[functions.analyze-prospection]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.sync-pipedrive]
verify_jwt = false

[functions.analyze-scripts]
verify_jwt = false
