project_id = "zuluogrlwqehvhxpqjok"

[functions.analyze-prospection]
verify_jwt = false

[functions.transcribe-audio]
verify_jwt = false

[functions.sync-pipedrive]
verify_jwt = false

[functions.analyze-scripts]
verify_jwt = false

[functions.sync-meetime]
verify_jwt = false

[functions.analyze-closer-meeting]
verify_jwt = false

[functions.sync-kommo]
verify_jwt = false
