import { useState, useMemo } from 'react';
import { MainLayout } from '@/components/layout/MainLayout';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { 
  GraduationCap, 
  CheckCircle2, 
  Clock, 
  AlertTriangle,
  User,
  Lightbulb,
  ArrowRight,
  Sparkles,
  Plus
} from 'lucide-react';
import { useDevelopmentPlans, useUpdateDevelopmentPlan, useAddDevelopmentPlan } from '@/hooks/useDevelopmentPlans';
import { useApp } from '@/contexts/AppContext';
import { DevelopmentPlan, PDIPriority, PDIStatus } from '@/types/goals';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';
import { CreatePDIDialog } from '@/components/development/CreatePDIDialog';

const priorityConfig: Record<PDIPriority, { label: string; color: string; icon: React.ElementType }> = {
  high: { label: 'Alta', color: 'bg-red-500/20 text-red-400 border-red-500/30', icon: AlertTriangle },
  medium: { label: 'Média', color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', icon: Clock },
  low: { label: 'Baixa', color: 'bg-blue-500/20 text-blue-400 border-blue-500/30', icon: Lightbulb },
};

const statusConfig: Record<PDIStatus, { label: string; color: string }> = {
  pending: { label: 'Pendente', color: 'bg-muted text-muted-foreground' },
  in_progress: { label: 'Em Progresso', color: 'bg-blue-500/20 text-blue-400' },
  completed: { label: 'Concluído', color: 'bg-green-500/20 text-green-400' },
};

const areaLabels: Record<string, string> = {
  abertura: 'Abertura',
  rapport: 'Rapport',
  spin: 'SPIN',
  bant: 'BANT',
  dores: 'Dores',
  geracaoValor: 'Geração de Valor',
  conducaoAgendamento: 'Condução p/ Agendamento',
  contornoObjecoes: 'Contorno de Objeções',
};

export default function DevelopmentPage() {
  const { data: plans = [], isLoading } = useDevelopmentPlans();
  const { sdrs, evaluations } = useApp();
  const updatePlan = useUpdateDevelopmentPlan();
  const addPlan = useAddDevelopmentPlan();

  const [selectedSdr, setSelectedSdr] = useState<string>('all');
  const [selectedTab, setSelectedTab] = useState<string>('pending');

  // Generate AI-based recommendations from evaluations
  const autoGeneratedPlans = useMemo(() => {
    const sdrWeakAreas: Record<string, { area: string; avgScore: number; count: number }[]> = {};

    evaluations.forEach((evaluation) => {
      if (!sdrWeakAreas[evaluation.sdrId]) {
        sdrWeakAreas[evaluation.sdrId] = [];
      }

      Object.entries(evaluation.scores).forEach(([area, score]) => {
        if (score < 70) {
          const existing = sdrWeakAreas[evaluation.sdrId].find(w => w.area === area);
          if (existing) {
            existing.avgScore = (existing.avgScore * existing.count + score) / (existing.count + 1);
            existing.count += 1;
          } else {
            sdrWeakAreas[evaluation.sdrId].push({ area, avgScore: score, count: 1 });
          }
        }
      });
    });

    const recommendations: { sdrId: string; weakArea: string; score: number; recommendation: string }[] = [];

    Object.entries(sdrWeakAreas).forEach(([sdrId, areas]) => {
      areas
        .sort((a, b) => a.avgScore - b.avgScore)
        .slice(0, 3)
        .forEach(({ area, avgScore }) => {
          recommendations.push({
            sdrId,
            weakArea: area,
            score: Math.round(avgScore),
            recommendation: getRecommendation(area),
          });
        });
    });

    return recommendations;
  }, [evaluations]);

  const filteredPlans = useMemo(() => {
    let result = plans;
    if (selectedSdr !== 'all') {
      result = result.filter(p => p.sdrId === selectedSdr);
    }
    if (selectedTab !== 'all' && selectedTab !== 'suggestions') {
      result = result.filter(p => p.status === selectedTab);
    }
    return result;
  }, [plans, selectedSdr, selectedTab]);

  const getSdr = (sdrId: string) => sdrs.find(s => s.id === sdrId);

  const handleStatusChange = (plan: DevelopmentPlan, newStatus: PDIStatus) => {
    updatePlan.mutate({
      id: plan.id,
      data: { status: newStatus },
    });
  };

  const handleCreateFromSuggestion = async (rec: { sdrId: string; weakArea: string; recommendation: string }) => {
    await addPlan.mutateAsync({
      sdrId: rec.sdrId,
      weakArea: rec.weakArea,
      recommendation: rec.recommendation,
      priority: 'high' as PDIPriority,
      status: 'pending' as PDIStatus,
    });
  };

  return (
    <MainLayout>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold flex items-center gap-2">
              <GraduationCap className="h-6 w-6 text-accent" />
              Plano de Desenvolvimento Individual
            </h1>
            <p className="text-muted-foreground">Acompanhe o desenvolvimento e recomendações de melhoria para cada SDR</p>
          </div>
          <CreatePDIDialog sdrs={sdrs} />
        </div>

        {/* Filters */}
        <div className="flex gap-4 items-center">
          <Select value={selectedSdr} onValueChange={setSelectedSdr}>
            <SelectTrigger className="w-48">
              <SelectValue placeholder="Filtrar por SDR" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">Todos os SDRs</SelectItem>
              {sdrs.map((sdr) => (
                <SelectItem key={sdr.id} value={sdr.id}>{sdr.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        <Tabs value={selectedTab} onValueChange={setSelectedTab}>
          <TabsList>
            <TabsTrigger value="pending">Pendentes</TabsTrigger>
            <TabsTrigger value="in_progress">Em Progresso</TabsTrigger>
            <TabsTrigger value="completed">Concluídos</TabsTrigger>
            <TabsTrigger value="suggestions">Sugestões IA</TabsTrigger>
          </TabsList>

          <TabsContent value="suggestions" className="mt-6">
            <Card className="glass-card mb-4">
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-lg">
                  <Sparkles className="h-5 w-5 text-accent" />
                  Recomendações Automáticas
                </CardTitle>
                <p className="text-sm text-muted-foreground">
                  Baseado nas últimas avaliações, identificamos as seguintes áreas de melhoria:
                </p>
              </CardHeader>
            </Card>

            {autoGeneratedPlans.length === 0 ? (
              <Card className="glass-card">
                <CardContent className="py-8 text-center text-muted-foreground">
                  Não há recomendações no momento. Realize mais avaliações para gerar insights.
                </CardContent>
              </Card>
            ) : (
              <div className="grid gap-4 md:grid-cols-2">
                {autoGeneratedPlans
                  .filter(p => selectedSdr === 'all' || p.sdrId === selectedSdr)
                  .map((rec, idx) => {
                    const sdr = getSdr(rec.sdrId);
                    return (
                      <Card key={idx} className="glass-card border-accent/20">
                        <CardContent className="pt-4 space-y-3">
                          <div className="flex items-center justify-between">
                            <div className="flex items-center gap-2">
                              <User className="h-4 w-4 text-muted-foreground" />
                              <span className="font-medium">{sdr?.name || 'SDR'}</span>
                            </div>
                            <Badge variant="outline" className="text-red-400 border-red-400/30">
                              Nota: {rec.score}
                            </Badge>
                          </div>
                          <div>
                            <span className="text-sm text-muted-foreground">Área:</span>
                            <span className="ml-2 font-medium">{areaLabels[rec.weakArea] || rec.weakArea}</span>
                          </div>
                          <div className="flex items-start gap-2 p-3 bg-secondary/50 rounded-lg">
                            <Lightbulb className="h-4 w-4 text-accent shrink-0 mt-0.5" />
                            <p className="text-sm">{rec.recommendation}</p>
                          </div>
                          <Button 
                            size="sm" 
                            variant="outline" 
                            className="w-full"
                            onClick={() => handleCreateFromSuggestion(rec)}
                            disabled={addPlan.isPending}
                          >
                            <Plus className="h-4 w-4 mr-2" />
                            Criar PDI
                          </Button>
                        </CardContent>
                      </Card>
                    );
                  })}
              </div>
            )}
          </TabsContent>

          {(['pending', 'in_progress', 'completed'] as PDIStatus[]).map((status) => (
            <TabsContent key={status} value={status} className="mt-6">
              {isLoading ? (
                <div className="text-center py-8 text-muted-foreground">Carregando...</div>
              ) : filteredPlans.length === 0 ? (
                <Card className="glass-card">
                  <CardContent className="py-12 text-center">
                    <GraduationCap className="h-12 w-12 text-muted-foreground mx-auto mb-4" />
                    <p className="text-muted-foreground">
                      Nenhum plano {statusConfig[status].label.toLowerCase()} encontrado
                    </p>
                    <p className="text-sm text-muted-foreground mt-2">
                      Clique em "Criar Plano" para adicionar um novo PDI
                    </p>
                  </CardContent>
                </Card>
              ) : (
                <div className="space-y-4">
                  {filteredPlans.map((plan) => {
                    const sdr = getSdr(plan.sdrId);
                    const priority = priorityConfig[plan.priority];
                    const PriorityIcon = priority.icon;

                    return (
                      <Card key={plan.id} className="glass-card">
                        <CardContent className="pt-4">
                          <div className="flex items-start justify-between gap-4">
                            <div className="flex-1 space-y-3">
                              <div className="flex items-center gap-3">
                                <Badge className={priority.color}>
                                  <PriorityIcon className="h-3 w-3 mr-1" />
                                  {priority.label}
                                </Badge>
                                <div className="flex items-center gap-1 text-sm text-muted-foreground">
                                  <User className="h-4 w-4" />
                                  <span>{sdr?.name || 'SDR'}</span>
                                </div>
                              </div>

                              <div>
                                <span className="text-sm text-muted-foreground">Área de Melhoria:</span>
                                <span className="ml-2 font-medium">{areaLabels[plan.weakArea] || plan.weakArea}</span>
                              </div>

                              <div className="flex items-start gap-2 p-3 bg-secondary/50 rounded-lg">
                                <ArrowRight className="h-4 w-4 text-accent shrink-0 mt-0.5" />
                                <p className="text-sm">{plan.recommendation}</p>
                              </div>

                              {plan.dueDate && (
                                <p className="text-xs text-muted-foreground">
                                  Prazo: {format(plan.dueDate, "dd 'de' MMMM", { locale: ptBR })}
                                </p>
                              )}
                            </div>

                            <div className="flex flex-col gap-2">
                              {plan.status === 'pending' && (
                                <Button
                                  size="sm"
                                  variant="outline"
                                  onClick={() => handleStatusChange(plan, 'in_progress')}
                                >
                                  Iniciar
                                </Button>
                              )}
                              {plan.status === 'in_progress' && (
                                <Button
                                  size="sm"
                                  className="gradient-accent"
                                  onClick={() => handleStatusChange(plan, 'completed')}
                                >
                                  <CheckCircle2 className="h-4 w-4 mr-1" />
                                  Concluir
                                </Button>
                              )}
                              {plan.status === 'completed' && plan.completedAt && (
                                <span className="text-xs text-green-400">
                                  Concluído em {format(plan.completedAt, 'dd/MM/yyyy')}
                                </span>
                              )}
                            </div>
                          </div>
                        </CardContent>
                      </Card>
                    );
                  })}
                </div>
              )}
            </TabsContent>
          ))}
        </Tabs>
      </div>
    </MainLayout>
  );
}

function getRecommendation(area: string): string {
  const recommendations: Record<string, string> = {
    abertura: 'Trabalhe em uma abertura mais impactante, mencionando o nome do lead e criando curiosidade nos primeiros segundos.',
    rapport: 'Dedique mais tempo para criar conexão pessoal antes de entrar no pitch. Faça perguntas sobre o contexto do lead.',
    spin: 'Pratique a sequência SPIN: Situação → Problema → Implicação → Necessidade. Use perguntas abertas para cada etapa.',
    bant: 'Mapeie melhor Budget, Authority, Need e Timeline logo no início para qualificar corretamente o lead.',
    dores: 'Aprofunde a investigação das dores do cliente antes de apresentar soluções. Faça o lead verbalizar o impacto do problema.',
    geracaoValor: 'Conecte cada funcionalidade a um benefício tangível. Use cases de sucesso e números concretos.',
    conducaoAgendamento: 'Seja mais direto no fechamento. Ofereça opções de horário específicas ao invés de perguntas abertas.',
    contornoObjecoes: 'Pratique a técnica LAER: Listen, Acknowledge, Explore, Respond. Não rebata objeções imediatamente.',
  };
  return recommendations[area] || 'Foque em melhorar esta área com prática e feedback contínuo.';
}
